# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
