# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170715_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='seo_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='blog/static/blog/img/contents/'),
        ),
    ]
