# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170720_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_square',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='blog.Image'),
            preserve_default=False,
        ),
    ]
