# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_image_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogtag',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
