# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-30 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170720_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='seo_title',
        ),
    ]
