# Generated by Django 2.2.5 on 2019-09-30 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180708_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='image',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_tag',
            field=models.ManyToManyField(to='blog.BlogTag'),
        ),
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(
                default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='blog.BlogCategory'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=markdownx.models.MarkdownxField(
                help_text='Markdown形式で書いてください。', verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.IntegerField(
                choices=[(0, '下書き'), (1, '公開')], default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='BlogPostTag',
        ),
    ]
