# Generated by Django 2.2.5 on 2019-10-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190930_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_square',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Image'),
        ),
    ]
