# Generated by Django 2.2.5 on 2019-10-28 06:49

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191004_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=markdownx.models.MarkdownxField(help_text='Markdown形式で書いてください。', null=True, verbose_name='本文'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ja',
            field=markdownx.models.MarkdownxField(help_text='Markdown形式で書いてください。', null=True, verbose_name='本文'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ja',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
