# Generated by Django 2.2.5 on 2019-10-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191028_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status_en',
            field=models.IntegerField(choices=[(0, '下書き'), (1, '公開')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status_ja',
            field=models.IntegerField(choices=[(0, '下書き'), (1, '公開')], default=0, null=True),
        ),
    ]
